import {
  User,
  Home,
  DollarSign,
  Shield,
  Award,
  Heart,
  Star,
  CheckCircle,
  Building,
  MapPin,
  Phone,
  Mail,
  Search,
  TrendingUp,
  Lock,
  Activity,
  Airplay,
  AlertCircle,
  AlertOctagon,
  AlertTriangle,
  AlignCenter,
  AlignJustify,
  AlignLeft,
  AlignRight,
  Anchor,
  Aperture,
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  AtSign,
  BarChart,
  Battery,
  Bell,
  Book,
  Bookmark,
  Box,
  Briefcase,
  Calendar,
  Camera,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Clock,
  Cloud,
  Code,
  Coffee,
  Command,
  Compass,
  Copy,
  CreditCard,
  Crop,
  Crosshair,
  Database,
  Delete,
  Download,
  Edit,
  Eye,
  Facebook,
  File,
  FileText,
  Film,
  Filter,
  Flag,
  Folder,
  Gift,
  Github,
  Globe,
  Grid,
  HardDrive,
  Hash,
  Headphones,
  HelpCircle,
  Image,
  Inbox,
  Info,
  Instagram,
  Layers,
  Layout,
  Link,
  Linkedin,
  List,
  Moon,
  Maximize,
  Menu,
  MessageCircle,
  MessageSquare,
  Mic,
  Minimize,
  Minus,
  Monitor,
  MoreHorizontal,
  MoreVertical,
  Move,
  Music,
  Navigation,
  Package,
  Paperclip,
  Pause,
  Play,
  Plus,
  PlusCircle,
  Pocket,
  Power,
  Printer,
  Radio,
  RefreshCcw,
  RefreshCw,
  Repeat,
  Rewind,
  Rss,
  Save,
  Scissors,
  Send,
  Server,
  Settings,
  Share,
  ShoppingBag,
  ShoppingCart,
  Shuffle,
  Sidebar,
  SkipBack,
  SkipForward,
  Slack,
  Slash,
  Sliders,
  Smartphone,
  Smile,
  Speaker,
  Square,
  StopCircle,
  Sun,
  Sunrise,
  Sunset,
  Tablet,
  Tag,
  Target,
  Terminal,
  Thermometer,
  ThumbsDown,
  ThumbsUp,
  ToggleLeft,
  ToggleRight,
  Trash,
  TrendingDown,
  Triangle,
  Truck,
  Tv,
  Twitter,
  Type,
  Umbrella,
  Underline,
  Unlock,
  Upload,
  UserCheck,
  UserMinus,
  UserPlus,
  UserX,
  Users,
  Video,
  VideoOff,
  Voicemail,
  Volume,
  Volume1,
  Volume2,
  VolumeX,
  Watch,
  Wifi,
  WifiOff,
  Wind,
  X,
  XCircle,
  Youtube,
  Zap,
  ZoomIn,
  ZoomOut,
} from "lucide-vue-next";
import type { Component } from "vue";

/**
 * Comprehensive icon mapping for all Lucide icons we support
 * Maps kebab-case names to PascalCase component names
 */
const iconMap: Record<string, Component> = {
  // Common icons
  user: User,
  home: Home,
  "dollar-sign": DollarSign,
  shield: Shield,
  award: Award,
  heart: Heart,
  star: Star,
  "check-circle": CheckCircle,
  building: Building,
  "map-pin": MapPin,
  phone: Phone,
  mail: Mail,
  search: Search,
  "trending-up": TrendingUp,
  lock: Lock,
  // Extended icon set
  activity: Activity,
  airplay: Airplay,
  "alert-circle": AlertCircle,
  "alert-octagon": AlertOctagon,
  "alert-triangle": AlertTriangle,
  "align-center": AlignCenter,
  "align-justify": AlignJustify,
  "align-left": AlignLeft,
  "align-right": AlignRight,
  anchor: Anchor,
  aperture: Aperture,
  archive: Archive,
  "arrow-down": ArrowDown,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up": ArrowUp,
  "at-sign": AtSign,
  "bar-chart": BarChart,
  battery: Battery,
  bell: Bell,
  book: Book,
  bookmark: Bookmark,
  box: Box,
  briefcase: Briefcase,
  calendar: Calendar,
  camera: Camera,
  check: Check,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  clock: Clock,
  cloud: Cloud,
  code: Code,
  coffee: Coffee,
  command: Command,
  compass: Compass,
  copy: Copy,
  "credit-card": CreditCard,
  crop: Crop,
  crosshair: Crosshair,
  database: Database,
  delete: Delete,
  download: Download,
  edit: Edit,
  eye: Eye,
  facebook: Facebook,
  file: File,
  "file-text": FileText,
  film: Film,
  filter: Filter,
  flag: Flag,
  folder: Folder,
  gift: Gift,
  github: Github,
  globe: Globe,
  grid: Grid,
  "hard-drive": HardDrive,
  hash: Hash,
  headphones: Headphones,
  "help-circle": HelpCircle,
  image: Image,
  inbox: Inbox,
  info: Info,
  instagram: Instagram,
  layers: Layers,
  layout: Layout,
  link: Link,
  linkedin: Linkedin,
  list: List,
  moon: Moon,
  maximize: Maximize,
  menu: Menu,
  "message-circle": MessageCircle,
  "message-square": MessageSquare,
  mic: Mic,
  minimize: Minimize,
  minus: Minus,
  monitor: Monitor,
  "more-horizontal": MoreHorizontal,
  "more-vertical": MoreVertical,
  move: Move,
  music: Music,
  navigation: Navigation,
  package: Package,
  paperclip: Paperclip,
  pause: Pause,
  play: Play,
  plus: Plus,
  "plus-circle": PlusCircle,
  pocket: Pocket,
  power: Power,
  printer: Printer,
  radio: Radio,
  "refresh-ccw": RefreshCcw,
  "refresh-cw": RefreshCw,
  repeat: Repeat,
  rewind: Rewind,
  rss: Rss,
  save: Save,
  scissors: Scissors,
  send: Send,
  server: Server,
  settings: Settings,
  share: Share,
  "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart,
  shuffle: Shuffle,
  sidebar: Sidebar,
  "skip-back": SkipBack,
  "skip-forward": SkipForward,
  slack: Slack,
  slash: Slash,
  sliders: Sliders,
  smartphone: Smartphone,
  smile: Smile,
  speaker: Speaker,
  square: Square,
  "stop-circle": StopCircle,
  sun: Sun,
  sunrise: Sunrise,
  sunset: Sunset,
  tablet: Tablet,
  tag: Tag,
  target: Target,
  terminal: Terminal,
  thermometer: Thermometer,
  "thumbs-down": ThumbsDown,
  "thumbs-up": ThumbsUp,
  "toggle-left": ToggleLeft,
  "toggle-right": ToggleRight,
  trash: Trash,
  "trending-down": TrendingDown,
  triangle: Triangle,
  truck: Truck,
  tv: Tv,
  twitter: Twitter,
  type: Type,
  umbrella: Umbrella,
  underline: Underline,
  unlock: Unlock,
  upload: Upload,
  "user-check": UserCheck,
  "user-minus": UserMinus,
  "user-plus": UserPlus,
  "user-x": UserX,
  users: Users,
  video: Video,
  "video-off": VideoOff,
  voicemail: Voicemail,
  volume: Volume,
  "volume-1": Volume1,
  "volume-2": Volume2,
  "volume-x": VolumeX,
  watch: Watch,
  wifi: Wifi,
  "wifi-off": WifiOff,
  wind: Wind,
  x: X,
  "x-circle": XCircle,
  youtube: Youtube,
  zap: Zap,
  "zoom-in": ZoomIn,
  "zoom-out": ZoomOut,
};

/**
 * Dynamically get a Lucide icon component by name
 * @param iconName - The name of the icon (e.g., "home", "user", "arrow-right")
 * @returns The icon component or null if not found
 */
export function getLucideIcon(iconName?: string | null): Component | null {
  if (!iconName || typeof iconName !== "string") {
    return null;
  }

  const normalizedName = iconName.toLowerCase().trim();
  const IconComponent = iconMap[normalizedName];

  if (IconComponent) {
    return IconComponent as Component;
  }

  if (process.dev) {
    console.warn(`Icon not found: "${iconName}"`);
  }

  return null;
}
